### ISSUE TITLE
грешки в funcs.php

### ISSUE THREAD

**Issue by ebullienc3** [impossibleartist/Case19#2]
[phpBB Debug] PHP Warning: in file D:/xampp/htdocs/includes/funcs.php on line 20: Undefined array key 1

Fatal error: Uncaught TypeError: mysqli_free_result(): Argument #1 ($result) must be of type mysqli_result, bool given in D:\xampp\htdocs\includes\funcs.php:129 Stack trace: #0 D:\xampp\htdocs\includes\funcs.php(129): mysqli_free_result(true) #1 D:\xampp\htdocs\index.php(12): require_once('D:\\xampp\\htdocs...') #2 {main} thrown in D:\xampp\htdocs\includes\funcs.php on line 129

Излиза ми тази грешка. Ако премахна секция "// Изтриване на старите реклами" излиза друга:

[phpBB Debug] PHP Warning: in file D:/xampp/htdocs/includes/funcs.php on line 20: Undefined array key 1

Fatal error: Uncaught TypeError: mysqli_free_result(): Argument #1 ($result) must be of type mysqli_result, bool given in D:\xampp\htdocs\includes\funcs.php:140 Stack trace: #0 D:\xampp\htdocs\includes\funcs.php(140): mysqli_free_result(true) #1 D:\xampp\htdocs\includes\funcs.php(142): unique_statistic() #2 D:\xampp\htdocs\index.php(12): require_once('D:\\xampp\\htdocs...') #3 {main} thrown in D:\xampp\htdocs\includes\funcs.php on line 140

След като изтрия и секцията "// Уникални посещения", която е на тези редове, системата се отваря без проблем. Как мога да оправя този проблем, за да не махам тези две фукции?

**Comment by HybridMind1337** [comment]
Здравей,
След това година ще бъде пусната новата версия на Case19, моля изчакайте
новата версия.

Поздрави, WEBOCEAN.INFO

На пт, 25.12.2020 г. в 19:33 ч. Malashev <notifications@github.com> написа:
